<a href="https://colab.research.google.com/github/soyoonjeong/SAI-ML-STUDY/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

# 넘파이 ndarray 개요 

In [2]:
# 넘파이의 array() 함수 : 인자를 입력받아 ndarray로 변환
array1 = np.array([[1,2,3],
                   [4,5,6]])
print(array1)
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # ndarray의 shape : ndarray의 열과 행의 크기를 튜플 형태로

[[1 2 3]
 [4 5 6]]
array1 type: <class 'numpy.ndarray'>
array1 array 형태: (2, 3)


In [3]:
array2 = np.array([1,2,3])
print(array2)
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
print('array2 array 차원:', array2.ndim) # ndarray의 ndim : ndarray의 차원

array3 = np.array([[1,2,3]])
print(array3)
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
print('array3 array 차원:', array3.ndim)

# array2와 array3는 동일한 데이터 건수를 가지고 있지만
# array2는 1차원 (3,) 데이터
# array3는 1개의 행과 3개의 열로 이루어진 2차원 (1,3) 데이터

[1 2 3]
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (3,)
array2 array 차원: 1
[[1 2 3]]
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array3 array 차원: 2


# ndarray의 데이터 타입

ndarray 내의 데이터 타입은 연산 특성상 같은 데이터 타입만 가능!<br>
만약 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환

In [4]:
list1 = [1,2,'test']
array1 = np.array(list1)
print(array1)
print(array1.dtype) # ndarray의 dtype : ndarray 내의 데이터 타입 확인
# int형 값과 문자열이 섞여 있는 리스트를 ndarray로 변경하면 모두 문자열로 변환

list2 = [1,2,3.0]
array2 = np.array(list2)
print(array2)
print(array2.dtype)
# int형 값과 float형이 섞여 있는 리스트를 ndarray로 변경하면 모두 float형으로 변환

['1' '2' 'test']
<U21
[1. 2. 3.]
float64


In [7]:
array_float = np.array([1.1,2.2,3.3])
array_int = array_float.astype('int32') # astype() : 인자로 원하는 타입을 문자열로 지정, 형변환
print(array_int, array_int.dtype)

[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

In [8]:
sequence_array = np.arange(10) # arange() : 인자는 stop 값, 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 반환
print(sequence_array)
print(sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [10]:
zero_array = np.zeros((4,5), dtype='int32') # zeros() : 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환
print(zero_array, zero_array.shape)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] (4, 5)


In [11]:
one_array = np.ones((4,9), dtype='int32') # ones() : 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1으로 채운 해당 shape를 가진 ndarray 반환
print(one_array, one_array.shape)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] (4, 9)


# ndarray의 차원과 크기를 변경하는 reshape()

In [14]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(5,2) # reshape() : ndarray를 특정 차원 및 크기로 변환
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array3 = array1.reshape(-1,5) # -1를 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환
print(array3, array3.shape)
array4 = array1.reshape(5,-1) 
print(array4, array4.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [21]:
array1 = np.arange(8)
print(array1, array1.shape)
array3d = array1.reshape((2,2,2))
print(array3d, array3d.shape)

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) # reshape(-1,1)은 원본 ndarray에 상관없이 2차원이고 1개의 칼럼을 가진 ndarray로 변환시킴
print(array5, array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print(array6, array6.shape)

[0 1 2 3 4 5 6 7] (8,)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)
